# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jefferson Alve's Portfolio
email: junior.jefferson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  M.Sc Computer Science and Software Engineering Student 
  at Institute of Exact and Natural Science of Federal University of Pará. 
  I have a lot of experience with software development since 1998. 
  I am proactive and dynamic with a critical mindset, I've been communications abilities, 
  teamwork and positive attitude. Focused on ability to recover from crisis situations and learn from them. 
  I about having a flexible mind and optimistic thinking with clear goals 
  and the certainty that everything will pass on problems of life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jeffjras
github_username:  jeffjras
linkedin_username: jeffjras

# Build settings
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  #- jekyll-remote-theme # add this line to the plugins list if you already have one


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
